### ISSUE TITLE
dist/index.d.ts file is missing

### ISSUE THREAD

**Issue by vsviridov** [kirillku/effector-easy-router#8]
Using version 0.0.7, my editor is complaining, saying that it is unable to find the declaration file for the module.

When I look into `node_modules/effector-easy-router/package.json`, I see that the `types` property points to the `./dist/index.d.ts`, however this file is missing.

**Comment by kirillku** [comment]
Thanks for pointing this out. Should be fixed in [0.0.8](https://github.com/kirillku/effector-easy-router/releases/tag/v0.0.8)
